### ISSUE TITLE
Json Serializer for Union Type

### ISSUE THREAD

**Issue by rubiktubik** [DavidArno/SuccincT#17]
Hello i'am using your great library but
now i'am coming to a problem when i need to serialize my objects.
My objects use the the `Union<T0,T1>` type.
Is there a example how to serialize with JSON.Net for example?

Michael

**Comment by DavidArno** [comment]
Oh, that's an interesting one. Bit embarrassing to admit, but it has never occurred to me that someone might want to serialise a union! 

So the honest answer is that Succinc&lt;T&gt; has no support currently, but it's certainly something that can be added.

**Comment by rubiktubik** [comment]
Too bad :-(
Then in the moment i need a way around it :-)

**Comment by DavidArno** [comment]
@rubiktubik,

Quick update on this.

I don't want to make Succinc&lt;T&gt; itself dependent on JSON.Net, therefore I'll create a new SuccincT.JSON nuget package, which will include Succinc&lt;T&gt; itself and support for serializing union types to JSON. That serialization will likely be achieved via custom `JsonConverter` and `ContractResolver` classes, rather than by annotating the types with JSON.Net specific attributes.

This'll mean you'd have to do something like:
````cs
string json = JsonConvert.SerializeObject(
    dataIncludingUnions,
    Formatting.Indented,
    new JsonSerializerSettings { ContractResolver = new SuccinctContractResolver() });
````
ie, whenever you need to serialize/deserialize any JSON that would include a union, you'd have to specify the custom `ContractResolver` class. Would that work for you?

**Comment by rubiktubik** [comment]
Yes!, that would be perfectly work!
I've seen similar approaches at other libraries.

Thank you for your effort.

**Comment by DavidArno** [comment]
Tasks required to complete this work:
- [x] Converter for `Option<>`
- [x] Converter for `Union<,>`
- [x] Converter for `Union<,,>`
- [x] Converter for `Union<,,,>`
- [x] Converter for `ValueOrError`
- [x] Converter for `Maybe<>` 
- [x] Converter for `None` 
- [x] Converter for `Unit` 
- [x] ContractResolver that handles the above types
- [x] Wiki updates to document how to use the converters and ContractResolver.
- [x] Create new nuget package that contains Succinc&lt;T&gt; and the JSON converters
- [x] Publish new nuget packages

**Comment by DavidArno** [comment]
[Version 2.2.0 of SuccincT.JSON is now available on nuget](https://www.nuget.org/packages/SuccincT.JSON/), which supplies JSON serialization support for Succinc\<T\> types.

This is the first release, but the version number has been set to coincide with the compatible release of Succinc\<T\> itself.

Please see the [JSON Serialization page](https://github.com/DavidArno/SuccincT/wiki/JsonSerialization) for details of its use.

**Comment by DavidArno** [comment]
[Version 2.2.0 of SuccincT.JSON is now available on nuget](https://www.nuget.org/packages/SuccincT.JSON/), which supplies JSON serialization support for Succinc\<T\> types.

This is the first release, but the version number has been set to coincide with the compatible release of Succinc\<T\> itself.

Please see the [JSON Serialization page](https://github.com/DavidArno/SuccincT/wiki/JsonSerialization) for details of its use.
