### ISSUE TITLE
TryGetValue for IDictionary<,>

### ISSUE THREAD

**Issue by megafinz** [DavidArno/SuccincT#19]
Currently that extension is defined for concrete Dictionary<,> type only. It would be nice if it works with all IDictionary<,> types.

**Comment by DavidArno** [comment]
OK, that should be easy. Wish you'd raised this a couple of days ago though as I could have added it to the v2.2.0 release that came out yesterday! 😀

**Comment by megafinz** [comment]
I wanted to do that myself and do a PR with a couple of other minor extensions that I use, but for some reason VS 2017 RC crashes when I try to open SuccincT.sln, VS 2015 complains about C# 7.0 language features and Rider is struggling with MSBuild scripts, so no luck with that.

**Comment by DavidArno** [comment]
v2.2.0 was created from the `serialization` branch, which is still compatible with VS2015. So if you pull that branch over to your repo and check it out, you should be able to make changes in VS2015 and submit a PR.

In what way does the `master` branch crash VS2017? Does it give any meaningful error?

If you have problems, let me know and I'll see if I can assist.

**Comment by megafinz** [comment]
`serialization` branch works well with both VS 2017 and 2015, but `master` just crashes IDE itself with no meaningful error. I tried starting VS with -Log switch, but I can't see any info about the crash in the log.

**Comment by DavidArno** [comment]
OK, thanks. I'll add a note that master might crash VS2017, whilst it's pre-release, to the README.

**Comment by megafinz** [comment]
Okay, I noticed that crash happens when SuccincT.Core project is being loaded. I removed it from the solution manually and now it opens just fine.

**Comment by megafinz** [comment]
Submitted PR.

**Comment by DavidArno** [comment]
v2.3.0 released.
