### ISSUE TITLE
Runtime Exception of type System.IO.FileNotFoundException 

### ISSUE THREAD

**Issue by pulivarthi55** [DavidArno/SuccincT#63]
Working on a .Net project targeting framework netstandard2.0 using SuccincT V3.2.0 library as a reference. At the time of build, I see no issues. But encountering the below runtime exception when code reached the SuccincT usage.

System.IO.FileNotFoundException : 'Could not load file or assembly 'SuccincT, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'

**Comment by DavidArno** [comment]
Which version of the framework/core are you using at runtime? I'm not at all sure why you get this issue, so I'd like to try and replicate it if possible.

**Comment by pulivarthi55** [comment]
Target Framework: .Net Standard
Version: 2.0

**Comment by DavidArno** [comment]
Sorry, I'm confused by this. I didn't think it possible to execute an app that targets net standard.

Would it be possible to try and create a minimum example of a project that exhibits this behaviour, so I can reproduce it? I've not had issues myself with a netstandard 2.0 library that references SuccincT that is in turn used by eg a framework 4.6.1 app, so I'm unsure why you are having an issue.

**Comment by DavidArno** [comment]
Closing this issue as there is insufficient info to replicate the reported problem.
